// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

// import { application } from "./application"


// import HelloController from "./hello_controller"
// application.register("hello", HelloController)


import { application } from "./application"
import applicationController from "./application_controller"
import StimulusReflex from "stimulus_reflex"

import AlertController from "./alert_controller"
application.register("alert", AlertController)

StimulusReflex.initialize(application, { applicationController, isolate: true })

// consider removing these options in production
StimulusReflex.debug = true
// end remove